language: python
python:
        - "3.5"
# command to install dependencies
install:
        - "pip install -e ."
# command to run tests
script: "python -c \"import phos\""

branches:
        only:
                - master
                - perseus-plugin
